services:
  todoapp_postgres:
    image: postgres:15-alpine
    restart: always
    hostname: myPostgres
    environment:
      - POSTGRES_USER=fedor
      - POSTGRES_PASSWORD=fedor_pass
      - POSTGRES_DB=todoapp
    ports:
      - 127.0.0.1:15432:5432
    volumes:
      - ./temp_files/postgresql_data:/var/lib/postgresql/data
    networks:
      local_todo_app:
        ipv4_address: 172.28.0.2

  api:
    image: ghcr.io/to-do-ers/to-do-ers/to-do_app-api:latest
    restart: always
    depends_on:
      - todoapp_postgres
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      local_todo_app:
        ipv4_address: 172.28.0.3


networks:
  local_todo_app:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
