environment: "development"

server:
  port: 8080
  host: "localhost"

database:
  host: "localhost"
  port: 15432
  name: "todoapp"
  user: "your_user_name"
  password: "your_database_password"
  migrationsDir: "./internal/storage/migrations"

jwt:
  secret: "your_jwt_secret"
  expiration: "24h"

redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password"