environment: "development"

server:
  port: 8080
  host: "localhost"

database:
  host: "localhost"
  port: 15432
  name: "todoapp"
  user: "fedor"
  password: "fedor_pass"
  migrationsDir: "./internal/storage/migrations"

jwt:
  secret: "1129qwerty!2911"
  expiration: "24h"