openapi: 3.0.0

info:
  title: Todo app OpenAPI spec
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Todoapp server

paths:
  /v1/auth/sign-up:
    post:
      summary: Метод для регистрации
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Пользователь зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/auth/sign-in:
    post:
      summary: Метод для аутентификации
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Пользователь залогинен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/auth/sign-out:
    get:
      summary: Метод для деаутентификации
      tags:
        - Auth
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Пользователь разлогинен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/users:
    get:
      summary: Метод для получения информации о пользователе
      tags:
       - Users
      security:
       - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ с информацией о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Метод для обновления информации пользователя
      tags:
        - Users
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: John
                user_pass:
                  type: string
                  example: aaa123
                user_email:
                  type: string
                  example: John@mail.go
      responses:
        "200":
          description: Обновление информации пользователя прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Метод для удаления пользователя
      tags:
        - Users
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Удаление прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/settings:
    get:
      summary: Метод получения настроек пользователя
      tags:
        - Settings
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ со списком настроек пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Метод для изменения настроек пользователя
      tags:
        - Settings
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Settings"
      responses:
        "200":
          description: Изменение настроек прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/tasks:
    get:
      summary: Метод для получения всех задач пользователя
      tags:
        - Tasks
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ со списком задач пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasks"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Метод для создания задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: Задача создана успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/tasks/{task_id}:
    get:
      summary: Метод для получения одной задачи пользователя
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      responses:
        "200":
          description: Успешный запрос на 1 задачу
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Метод для изменения задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: Задача успешно изменена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Метод для удаления задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
            example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      responses:
        "200":
          description: Задача успешно удалена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: cookie
      description: Cookie-based аутентификация

  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        user_name:
          type: string
          example: John
        user_pass:
          type: string
          example: aaa123
        user_email:
          type: string
          example: John@mail.go

    Settings:
      type: object
      properties:
        default_tz:
          type: string
          example: UTC
        default_duration:
          type: integer
          example: 43200

    Task:
      type: object
      properties:
        task_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        parent_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        owner_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        start_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        end_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        title:
          type: string
          example: Название
        description:
          type: string
          example: Описание
        completed_at:
          type: boolean
          example: true
        subtasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"

    Tasks:
      type: array
      items:
        $ref: "#/components/schemas/Task"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: success
