openapi: 3.0.0

info:
  title: Todo app OpenAPI spec
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ToDoApp server

paths:
  /v1/auth/sign-up:
    post:
      summary: Регистрация
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignUp"
      responses:
        "201":
          description: Пользователь зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/auth/sign-in:
    post:
      summary: Аутентификация
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignIn"
      responses:
        "200":
          description: Пользователь залогинен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/sign-out:
    post:
      summary: Разлогин
      tags:
        - Auth
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Пользователь разлогинен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/users:
    get:
      summary: Получение информации о пользователе
      tags:
        - Users
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ с информацией о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Обновление информации пользователя
      tags:
        - Users
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: John
                  nullable: true
                  description: Может быть null, если не изменяется
                user_pass:
                  type: string
                  example: aaa123
                  nullable: true
                  description: Может быть null, если не изменяется
                user_email:
                  type: string
                  example: John@mail.go
                  nullable: true
                  description: Может быть null, если не изменяется
      responses:
        "200":
          description: Обновление информации пользователя прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Удаление пользователя
      tags:
        - Users
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Удаление прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/settings:
    get:
      summary: Получение настроек пользователя
      tags:
        - Settings
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ со списком настроек пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Изменение настроек пользователя
      tags:
        - Settings
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SettingsUpdate"
              description: Должно быть заполнено хотя бы одно поле
      responses:
        "200":
          description: Изменение настроек прошло успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/tasks:
    get:
      summary: Получение всех задач пользователя
      tags:
        - Tasks
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешный ответ со списком задач пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TasksResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Создание задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "201":
          description: Задача создана успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/private/tasks/{task_id}:
    get:
      summary: Получение одной задачи пользователя
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      responses:
        "200":
          description: Успешный запрос на 1 задачу
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Изменение задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
              description: Должно быть заполнено хотя бы одно поле

      responses:
        "200":
          description: Задача успешно изменена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Удаление задачи
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Идентификатор задачи
          schema:
            type: string
            example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
      responses:
        "200":
          description: Задача успешно удалена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
      description: Cookie-based аутентификация

  schemas:
    UserSignUp:
      type: object
      required:
        - user_name
        - user_pass
        - user_email
      properties:
        user_name:
          type: string
          example: John
        user_pass:
          type: string
          example: aaa123
        user_email:
          type: string
          example: John@mail.go

    UserSignIn:
      type: object
      required:
        - user_pass
        - user_email
      properties:
        user_pass:
          type: string
          example: aaa123
        user_email:
          type: string
          example: John@mail.go

    UserResponse:
      type: object
      properties:
        user_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        user_name:
          type: string
          example: John
        user_email:
          type: string
          example: John@mail.go

    Settings:
      type: object
      properties:
        time_duration:
          type: number
          example: 43200
        user_tz:
          type: string
          example: UTC+1

    SettingsUpdate:
      type: object
      properties:
        time_duration:
          type: number
          example: 43200
          nullable: true
        user_tz:
          type: string
          example: UTC+1
          nullable: true

    TaskResponse:
      type: object
      properties:
        task_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        parent_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        owner_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        start_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        end_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        title:
          type: string
          example: Название
        description:
          type: string
          example: Описание
        completed_at:
          type: boolean
          example: true
        subtasks:
          type: array
          items:
            $ref: "#/components/schemas/TaskResponse"

    TasksResponse:
      type: array
      items:
        $ref: "#/components/schemas/TaskResponse"

    TaskRequest:
      type: object
      properties:
        parent_id:
          type: string
          example: b6609ddd-95f4-42f0-993e-7f07f3fa1d5b
        start_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        end_at:
          type: string
          format: date-time
          example: 2025-10-11T18:52:19.674Z
        title:
          type: string
          example: Название
        description:
          type: string
          example: Описание
        completed_at:
          type: boolean
          example: true

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: successful
