name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  GO_VERSION: '1.25.0'
  PROJECT_NAME: 'todoapp'

jobs:
  validate:
    name: Validate dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Up GO
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Verify dependencies
      run: |
        go mod verify
        go mod tidy

    - name: Check code formatting
      run: |
        test -z $(gofmt -l .)